# 数据库配置
datasource:
  dbname: test
  host: 127.0.0.1:3306
  password: test
  username: test

spring:
  redis:
    host: 127.0.0.1 # Redis服务器地址
    port: 63790 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    database: 0 # Redis数据库索引（默认为0）
    timeout: 30000ms
    lettuce:
      pool:
        max-idle: 10   # 连接池中的最大空闲连接
        min-idle: 0   # 连接池中的最小空闲连接
        max-active: 100  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）

# 全局日志级别
log:
  global:
    level: dubug